// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID        uuid.UUID
	Score     int32
	Accuracy  string
	CreatedAt time.Time
	PlayerID  uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	CreatedAt      time.Time
}
